packages:
  - apps/*
  - packages/*

catalog:
  "@eslint/eslintrc": ^3.1.0
  "@eslint/js": ^9.12.0
  "@tsconfig/node20": ">=20 <=20.16"
  "@types/node": ">=20 <=20.16"
  "@types/uuid": ~10.0
  dotenv: ^16.4.5
  eslint: ^9.12.0
  eslint-plugin-react: ^7.37.0
  eslint-plugin-react-hooks: ^5.0.0
  openai: ^4.55.4
  prettier: ^3.3.3
  "promised-sqlite3": ^2.1.0
  "sqlite3": ^5.1.7
  tslib: ^2.6.3
  ts-node: ^10.9.2
  typescript: ^5.5.4
  typescript-eslint: ^8.8.1
  uuid: ^10.0.0
  zod: ^3.23.8
  "zod-validation-error": ^3.3.1
